### ISSUE TITLE
Turn off alarm vibration in settings

### ISSUE THREAD

**Issue by yephny** [qw123wh/new-clock#14]
I don't like my phone vibrating, so I have to manually disable vibration for each alarm I set because it's on by default. It'd be a good idea to have an option in settings where you can configure default alarm behavior like vibration.

**Comment by qw123wh** [comment]
Ok I'll see if I can do something

**Comment by yephny** [comment]
Another option is to have vibration off by default just like repeat.

**Comment by yephny** [comment]
It looks like vibration is there for the buttons in stopwatch and timer as well.
