### ISSUE TITLE
Disable upcoming alarm notification

### ISSUE THREAD

**Issue by yephny** [qw123wh/new-clock#16]
The app notifies you of upcoming alarms and there is no setting to turn it off. You could ad d a switch in settings to disable it, notifications aren't necessary at all.

**Comment by qw123wh** [comment]
These notifications can be deactivated in the settings it's very simple. For me they are essential, then if I delete the notification from the source code, the alarm will no longer sound I have already done some tests.

**Comment by qw123wh** [comment]
![Uploading 4243635D-8FCA-4C7C-A73B-21EBB67BF5D4.jpeg…]()

**Comment by yephny** [comment]
Oh, if that's the case, then no problem. I disabled the notifications myself already, just thought it would be more practical if there was a switch for it in the settings. Thanks.
