### ISSUE TITLE
Add option in settings to change theme

### ISSUE THREAD

**Issue by qw123wh** [qw123wh/new-clock#2]
The options for the theme must be light / dark / system

**Comment by yephny** [comment]
Are you planning to make the dark theme pitch black with `#000000` as the background like it is now?

**Comment by qw123wh** [comment]
The dark theme is already totally black how can you come here:
https://github.com/qw123wh/new-clock/blob/master/res/values-night/colors.xml

<color name="color_background">#000000</color

The only problem that is activated only when the dark mode is active at the system level.  I am trying with the help of others to add the option in the settings but it is still buggy and does not work.

**Comment by yephny** [comment]
I'm glad that you're back.

**Comment by qw123wh** [comment]
the source code has been updated with material you thanks and this theme option has also been added thanks to PR # 22
