### ISSUE TITLE
The alarm does not fire and work on Xiaomi phones

### ISSUE THREAD

**Issue by kia1349** [qw123wh/new-clock#20]
I installed and tested the app on my Xiaomi 11 Ultra phone.
In the settings, I set the program to auto-start.
And I put the battery without any restrictions
Sometimes the alarm does not work
Sometimes it works but the phone screen does not turn on

**Comment by kia1349** [comment]
thanks a loat , i am developer too and we need to source that works on xiaomi too
MIUI Optimization missing from Developer options in miui 13 and the MIUI Optimization toggle has gone missing seemingly after the latest MIUI 12.0.7/12.0.5/13.0.4

i test fdroid version and informed you

**Comment by qw123wh** [comment]
@kia1349 I tried the app on miui again, it's miui 11. But I think it can be fine.  You have to go to the settings, applications, clock and give all the permissions where other permissions are written, then disable the battery saver .. I'll send you screenshots
![78997DE0-C517-44F4-A697-7CF3230610E3](https://user-images.githubusercontent.com/59417474/171988164-39fe4b83-d8ae-4c8a-a556-c201b34ea419.jpeg)
![E97C4667-00D3-4C02-AF46-93551A98FF73](https://user-images.githubusercontent.com/59417474/171988168-1be1de45-5bda-454d-af3e-786ce11babcb.jpeg)
![B580D9E3-9CEA-43DA-B620-040E4D4A5725](https://user-images.githubusercontent.com/59417474/171988170-60bf35ba-8b91-4ee0-b9d1-672397b61041.jpeg)

**Comment by qw123wh** [comment]
Since you are a developer, feel free to add some features that can improve the app.  For example if I could put an option in the settings to select the theme: "automatic / white / dark".  Currently the behavior is always on automatic.

**Comment by kia1349** [comment]
thank again.i tried these settings, alarm work but activity "AlarmActivity" not show.it can not turn on screen and show on screen when screen locked nwith pin or finger print
but i try again

**Comment by kia1349** [comment]
about  the theme: "automatic / white / dark" , i try too
thanks for sharing your code code and idea

**Comment by qw123wh** [comment]
I found a guide to make miui optimization reappear.  Go into developer settings and click "reset to default values" a couple of times at this point it should reappear.  I don't know if this guide works, just give it a try.  Perhaps miui has worsened in terms of restrictions in third-party apps, however in mui 11 there is no such bug.

**Comment by qw123wh** [comment]
> about the theme: "automatic / white / dark" , i try too
> thanks for sharing your code and idea

Thanks

**Comment by kia1349** [comment]
> I found a guide to make miui optimization reappear. Go into developer settings and click "reset to default values" a couple of times at this point it should reappear. I don't know if this guide works, just give it a try. Perhaps miui has worsened in terms of restrictions in third-party apps, however in mui 11 there is no such bug.

I have done this method before. This option is in the settings list, but unfortunately it has been disabled by Xiaomi.
![Screenshot_2022-06-04-17-45-49-147_com android settings](https://user-images.githubusercontent.com/10990724/172001146-e64fb5a0-821d-41eb-838a-1b4ff756eab5.jpg)

**Comment by kia1349** [comment]
> Since you are a developer, feel free to add some features that can improve the app. For example if I could put an option in the settings to select the theme: "automatic / white / dark". Currently the behavior is always on automatic.


hi again qw123wh
i add option in the main screen to select the theme: "automatic / white / dark".
i add this to fdroid 
you can test it seperately in your computer and if it is ok then merge to your app

i sent source code to your email:
[qw123whreuvkjs@gmail.com](mailto:qw123whreuvkjs@gmail.com)

**Comment by qw123wh** [comment]
Done
