### ISSUE TITLE
cannot set in targetSdk 33

### ISSUE THREAD

**Issue by uchup** [qw123wh/new-clock#27]
me update targetSdk 33
error :
java.lang.IllegalStateException: Not allowed to start service Intent { act=STOP_ALARM ...

E/Zygote: isWhitelistProcess - Process is Whitelisted
E/Zygote: accessInfo : 1
3689-3689/? I/.best.deskcloc: Late-enabling -Xcheck:jni
3689-3689/com.best.deskclock W/.best.deskcloc: Accessing hidden field Landroid/os/Trace;->TRACE_TAG_APP:J (light greylist, reflection)
3689-3689/com.best.deskclock W/.best.deskcloc: Accessing hidden method Landroid/os/Trace;->isTagEnabled(J)Z (light greylist, reflection)
3689-3689/com.best.deskclock I/DigitalWidgetProvider: onReceive: Intent { act=android.app.action.NEXT_ALARM_CLOCK_CHANGED flg=0x21000010 cmp=com.best.deskclock/com.best.alarmclock.DigitalAppWidgetProvider }

**Comment by qw123wh** [comment]
if you touch any value between target sdk, min sdk, the alarm does not sound it is a problem with the aosp clock source.

**Comment by qw123wh** [comment]
Done
