### ISSUE TITLE
Material You design suggestion

### ISSUE THREAD

**Issue by BluePixel4k** [qw123wh/new-clock#29]
Thank you for implementing the Material You design into this app. It's awesome. 🔥 

I have a suggestion to improve the design a bit.
Can you add circles to the num pad in the Timer tab?
<img src="https://user-images.githubusercontent.com/77979781/185356892-77355189-feb2-4a33-80d0-11165fbd9c79.png" width="300" />

**Comment by qw123wh** [comment]
material you was implemented by @edodson84 try his fork, the two apps can be installed at the same time, have different package names, they should not conflict

https://github.com/edodson84/new-clock

**Comment by BluePixel4k** [comment]
Thank you for the suggestion. I will take a look at it.

**Comment by qw123wh** [comment]
Done
