### ISSUE TITLE
Material You color palette with MonetCompat

### ISSUE THREAD

**Issue by BluePixel4k** [qw123wh/new-clock#30]
I would love to see the Material You color palette in this app.
I found the repository from Kieron Quinn, it's looks like an easy way to implement the monet colors:
https://github.com/KieronQuinn/MonetCompat

It's written in Kotlin, sadly I don't know how difficult it is to implement it in Java.

It also supports older Android versions below 12.

**Comment by qw123wh** [comment]
There are many things to improve, unfortunately I don't have much knowledge about it, I hope someone can solve it with some PR

**Comment by qw123wh** [comment]
Done
