### ISSUE TITLE
[Bug] expired timer and alarm notifications are not completely filled

### ISSUE THREAD

**Issue by BluePixel4k** [qw123wh/new-clock#31]
On longer screens, the bottom is not filled:
<img src="https://user-images.githubusercontent.com/77979781/188725601-a9679bdd-bbc8-4ec8-afb9-d4f0386262a7.png" width="200" /> <img src="https://user-images.githubusercontent.com/77979781/188725605-cf6574e3-e0fd-41d1-a047-b410c74a0697.png" width="200" />

**Comment by qw123wh** [comment]
There should be an option in the system settings of the phone, called "full screen app", search for it and enable the app concerned

**Comment by BluePixel4k** [comment]
I didn't find the "full screen app" setting, only the "display over other apps", but the clock app isn't listed there.

**Comment by qw123wh** [comment]
Done
