### ISSUE TITLE
hello developer

### ISSUE THREAD

**Issue by adilronaq** [qw123wh/new-clock#38]
i found issue in this app its big issue and app not work proper when set alarm and remove the app from background then alram not working.... i found this issue in your code but your previous app ([new-clock-fdroid](https://github.com/qw123wh/new-clock-fdroid)) its work properly in new-clock app its not working ple resolve this issue and update the app thks advance

**Comment by qw123wh** [comment]
Done

**Comment by adilronaq** [comment]
thks bro i asked you one thing where you changing in this projects???

**Comment by qw123wh** [comment]
The project is being updated, at the moment the problem has been solved, many things have been fixed, you can see them from the commits.  A new version will be released when it is ready.

**Comment by adilronaq** [comment]
sir i donwload you updated source code and run the project and et the alarm
set time (5 mint above of current time like current time is 10:00 am and i
set alram at 10:05 am) when i closed the app foregpound and background both
the at 10:10am time reached thent he alarm not play and alarmscreen not
show and does not play alarm i asked you did you resolve this issue ???

**Comment by adilronaq** [comment]
> Done

sir you chk it your app after update it... Alarm Functionality not working on open ads and background also.... chk your code and test it and tell mie bro

**Comment by qw123wh** [comment]
The error you are telling me about is only experienced by you. The version has not been released, the updated fork however is this https://github.com/BlackyHawky/Clock you need to generate an apk with android studio. You have to tell me what phone you have, Android version, I would also need a log, otherwise I can't solve it. To work correctly the app you must give all the necessary permissions such as "deactivate battery saving" and more. If you also have restrictions like on Miui, it's Xiaomi's fault.

**Comment by adilronaq** [comment]
bro i test the app at android 8 ,10, 11,12, 13 also all devices alarm not
show if the app is removed from the background... if android sdk version
above 30+ alarm not working if set it into below 30 its show alarm and
working if app is open and remove background also

**Comment by qw123wh** [comment]
I have already explained to you that if you do not remove the battery optimization it will not play and I have already explained to you that the app has not been released. There are other open-source clock apps try other apps. This will never work for you. Change app and don't write anymore
