### ISSUE TITLE
Request to add feature to set default alarm ringtone in settings

### ISSUE THREAD

**Issue by vishalscodes** [qw123wh/new-clock#42]
**Is your feature request related to a problem? Please describe.**
Given in title. It should be similar to how there is such an option for timers.

**Describe the solution you'd like**
An option for the same.

**Use case**
To avoid effort.

![Screenshot_20240413_110424_com chen deskclock](https://github.com/qw123wh/new-clock/assets/104351431/a3812e37-32e5-4e29-bb5d-6fcaad3a983f)

**Comment by qw123wh** [comment]
That's a good idea, this is the updated reposity https://github.com/BlackyHawky/Clock

Open the same issue there. We are already working on adding the ability to choose music on the device, but it will take some time

**Comment by BlackyHawky** [comment]
@qw123wh You can close this as it is implemented in my repository.

**Comment by qw123wh** [comment]
Completed
